import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const clashDisplay = localFont({
  src: [
    {
      path: './fonts/ClashDisplay-Semibold.eot',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/ClashDisplay-Semibold.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/ClashDisplay-Semibold.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/ClashDisplay-Semibold.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clashDisplay.className}
      >
        {children}
      </body>
    </html>
  );
}
